version: '3.4'

networks:
  pj-net:
    external:
      name: example-core-shared

services:
  pj-example-api:
    image: pj-example-api
    build:
      context: ..
      dockerfile: src/PJ.Example.API/Dockerfile
    ports:
      - 9998:80
      - 9999:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWT__JWTKEY=asdv234234^&%&^%&^hjsdfb2%%%
      - JWT__JWTISSUER=http://localhost:9998/
      - JWT__JWTAUDIENCE=http://localhost:9998/
      - DBOPTIONS__DBCONNECTIONSTRING=server=pj-example-db;database=PJ-Example-MS;User ID=sa;Password=Passw0rd;MultipleActiveResultSets=true;Encrypt=False
      - ENCRYPTIONOPTIONS__PASSPHRASE=BWM8DMLALrFH2bL02Cgq
    volumes:
      - ../../logs:/var/log:rw
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - pj-net
    restart: always